export const TestData = [
  {
    id: '#title:"“오픈AI 직원 90%, 이사 전원 사임 촉구…안되면 MS 가겠다”",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=47Cpozx84R",date:"23.11.21 06:32",childCategory:"청렴/투명경영(GOVERNANCE)",',
    parentCategory: "ESG 뉴스",
    childCategory: "청렴/투명경영(GOVERNANCE)",
    reporter: "뉴스럴",
    title: "“오픈AI 직원 90%, 이사 전원 사임 촉구…안되면 MS 가겠다”",
    link: "https://www.neusral.com/r?n=47Cpozx84R",
    date: "23.11.21 06:32",
    description: undefined,
  },
  {
    id: '#title:"전교조, 작년 수입 156억… 노조 전임자에 84억 사용",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=YKCRY7Lyem",date:"23.11.21 04:11",childCategory:"청렴/투명경영(GOVERNANCE)",',
    parentCategory: "ESG 뉴스",
    childCategory: "청렴/투명경영(GOVERNANCE)",
    reporter: "뉴스럴",
    title: "전교조, 작년 수입 156억… 노조 전임자에 84억 사용",
    link: "https://www.neusral.com/r?n=YKCRY7Lyem",
    date: "23.11.21 04:11",
    description: undefined,
  },
  {
    id: `#title:"'금융사고 CEO 처벌' '산은 부산이전법' 통과되나..기촉법도 재논의",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=Z2C0oGMNBP",date:"23.11.21 05:00",childCategory:"청렴/투명경영(GOVERNANCE)",`,
    parentCategory: "ESG 뉴스",
    childCategory: "청렴/투명경영(GOVERNANCE)",
    reporter: "뉴스럴",
    title: "'금융사고 CEO 처벌' '산은 부산이전법' 통과되나..기촉법도 재논의",
    link: "https://www.neusral.com/r?n=Z2C0oGMNBP",
    date: "23.11.21 05:00",
    description: undefined,
  },
  {
    id: '#title:"코인시장도 기울어진 운동장… 큰손 고래, 업비트 코인 90% 보유",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=p0CdaBPLQ3",date:"23.11.21 06:01",childCategory:"청렴/투명경영(GOVERNANCE)",',
    parentCategory: "ESG 뉴스",
    childCategory: "청렴/투명경영(GOVERNANCE)",
    reporter: "뉴스럴",
    title: "코인시장도 기울어진 운동장… 큰손 고래, 업비트 코인 90% 보유",
    link: "https://www.neusral.com/r?n=p0CdaBPLQ3",
    date: "23.11.21 06:01",
    description: undefined,
  },
  {
    id: '#title:"이자도 못내는 기업들… 은행 ‘깡통 대출’ 급증",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=LBCp1Ed8QY",date:"23.11.21 03:03",childCategory:"청렴/투명경영(GOVERNANCE)",',
    parentCategory: "ESG 뉴스",
    childCategory: "청렴/투명경영(GOVERNANCE)",
    reporter: "뉴스럴",
    title: "이자도 못내는 기업들… 은행 ‘깡통 대출’ 급증",
    link: "https://www.neusral.com/r?n=LBCp1Ed8QY",
    date: "23.11.21 03:03",
    description: undefined,
  },
  {
    id: '#title:"비트코인, 3만7000달러 돌파 후 소폭 상승세… FOMC 의사록 주목",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=MLC6zLJB8A",date:"23.11.21",childCategory:"가상자산/월렛/거래소",',
    parentCategory: "ESG 뉴스",
    childCategory: "가상자산/월렛/거래소",
    reporter: "뉴스럴",
    title: "비트코인, 3만7000달러 돌파 후 소폭 상승세… FOMC 의사록 주목",
    link: "https://www.neusral.com/r?n=MLC6zLJB8A",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"코인시장도 기울어진 운동장… 큰손 고래, 업비트 코인 90% 보유",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=p0CdaBPLQ3",date:"23.11.21",childCategory:"가상자산/월렛/거래소",',
    parentCategory: "ESG 뉴스",
    childCategory: "가상자산/월렛/거래소",
    reporter: "뉴스럴",
    title: "코인시장도 기울어진 운동장… 큰손 고래, 업비트 코인 90% 보유",
    link: "https://www.neusral.com/r?n=p0CdaBPLQ3",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: `#title:"비트코인 이어 '이더리움 현물 ETF' 신청 러시…시장 영향은",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=Z2C0oGMeRW",date:"23.11.21",childCategory:"가상자산/월렛/거래소",`,
    parentCategory: "ESG 뉴스",
    childCategory: "가상자산/월렛/거래소",
    reporter: "뉴스럴",
    title: "비트코인 이어 '이더리움 현물 ETF' 신청 러시…시장 영향은",
    link: "https://www.neusral.com/r?n=Z2C0oGMeRW",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: `#title:"샘 알트먼 소식에 20% 급등락…'유명무실' 월드코인 널뛰기",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=zRCyJmKddp",date:"23.11.20",childCategory:"가상자산/월렛/거래소",`,
    parentCategory: "ESG 뉴스",
    childCategory: "가상자산/월렛/거래소",
    reporter: "뉴스럴",
    title: "샘 알트먼 소식에 20% 급등락…'유명무실' 월드코인 널뛰기",
    link: "https://www.neusral.com/r?n=zRCyJmKddp",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"\\"코인 투자 결과 한눈에 \\"…코인원, 자산분석 서비스 출시",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=aVCVRMoj7r",date:"23.11.20",childCategory:"가상자산/월렛/거래소",',
    parentCategory: "ESG 뉴스",
    childCategory: "가상자산/월렛/거래소",
    reporter: "뉴스럴",
    title: '"코인 투자 결과 한눈에 "…코인원, 자산분석 서비스 출시',
    link: "https://www.neusral.com/r?n=aVCVRMoj7r",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"암호화폐 거래소 불리시, 코인데스크 인수",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=mxC4MwVO1R",date:"23.11.21",childCategory:"가상자산/월렛/거래소",',
    parentCategory: "ESG 뉴스",
    childCategory: "가상자산/월렛/거래소",
    reporter: "뉴스럴",
    title: "암호화폐 거래소 불리시, 코인데스크 인수",
    link: "https://www.neusral.com/r?n=mxC4MwVO1R",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"미술품 조각투자 등 STO 장내시장 거래 규제 샌드박스 승인 눈앞",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=02CzLoYaJ3",date:"23.11.21",childCategory:"NFT/STO",',
    parentCategory: "ESG 뉴스",
    childCategory: "NFT/STO",
    reporter: "뉴스럴",
    title: "미술품 조각투자 등 STO 장내시장 거래 규제 샌드박스 승인 눈앞",
    link: "https://www.neusral.com/r?n=02CzLoYaJ3",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"한국투자증권, 업계 최초 토큰증권 발행 인프라 구축",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=ROCyaRzGKm",date:"23.11.20",childCategory:"NFT/STO",',
    parentCategory: "ESG 뉴스",
    childCategory: "NFT/STO",
    reporter: "뉴스럴",
    title: "한국투자증권, 업계 최초 토큰증권 발행 인프라 구축",
    link: "https://www.neusral.com/r?n=ROCyaRzGKm",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"가상자산 훈풍에… 웹3 게임·플랫폼 다시 날아오를 채비",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=68Ce0yX036",date:"23.11.20",childCategory:"NFT/STO",',
    parentCategory: "ESG 뉴스",
    childCategory: "NFT/STO",
    reporter: "뉴스럴",
    title: "가상자산 훈풍에… 웹3 게임·플랫폼 다시 날아오를 채비",
    link: "https://www.neusral.com/r?n=68Ce0yX036",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"오사카 디지털 거래소 일본 최초 토큰증권 상장",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=bXC8GOdBWZ",date:"23.11.21",childCategory:"NFT/STO",',
    parentCategory: "ESG 뉴스",
    childCategory: "NFT/STO",
    reporter: "뉴스럴",
    title: "오사카 디지털 거래소 일본 최초 토큰증권 상장",
    link: "https://www.neusral.com/r?n=bXC8GOdBWZ",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: `#title:"블룸버그 \\"美당국, '돈세탁' 바이낸스에 벌금 5조원 부과·수사종결 논의\\"",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=VwCyo1qjrb",date:"23.11.21",childCategory:"정책/규제",`,
    parentCategory: "ESG 뉴스",
    childCategory: "정책/규제",
    reporter: "뉴스럴",
    title: `블룸버그 "美당국, '돈세탁' 바이낸스에 벌금 5조원 부과·수사종결 논의"`,
    link: "https://www.neusral.com/r?n=VwCyo1qjrb",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: `#title:"'코인 상장 청탁' 혐의 빗썸홀딩스 대표·안성현 첫 재판",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=Z2C0oGMOkq",date:"23.11.21",childCategory:"정책/규제",`,
    parentCategory: "ESG 뉴스",
    childCategory: "정책/규제",
    reporter: "뉴스럴",
    title: "'코인 상장 청탁' 혐의 빗썸홀딩스 대표·안성현 첫 재판",
    link: "https://www.neusral.com/r?n=Z2C0oGMOkq",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"\\"클래식은 영원했다\\" 수치로 입증한 폴로 랄프로렌의 부활",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=eWCWL1apaW",date:"23.11.21",childCategory:"패션/뷰티",',
    parentCategory: "ESG 뉴스",
    childCategory: "패션/뷰티",
    reporter: "뉴스럴",
    title: '"클래식은 영원했다" 수치로 입증한 폴로 랄프로렌의 부활',
    link: "https://www.neusral.com/r?n=eWCWL1apaW",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: `#title:"\\"캐시미어 1등급에 독특한 컬러…일라일, '니트 맛집' 이유 있죠\\"",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=02CzLowbZ3",date:"23.11.20",childCategory:"패션/뷰티",`,
    parentCategory: "ESG 뉴스",
    childCategory: "패션/뷰티",
    reporter: "뉴스럴",
    title: `"캐시미어 1등급에 독특한 컬러…일라일, '니트 맛집' 이유 있죠"`,
    link: "https://www.neusral.com/r?n=02CzLowbZ3",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"日 진출 중인 K 뷰티 브랜드 '롱런 전략' 필요",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=47CpozxLzW",date:"23.11.20",childCategory:"패션/뷰티",`,
    parentCategory: "ESG 뉴스",
    childCategory: "패션/뷰티",
    reporter: "뉴스럴",
    title: "日 진출 중인 K 뷰티 브랜드 '롱런 전략' 필요",
    link: "https://www.neusral.com/r?n=47CpozxLzW",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"\\"젊어진 새우깡·더 매운 신라면\\"…MZ 입맛 따라 변화하는 식품업계 스테디셀러",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=gpCkMwNOLV",date:"23.11.21",childCategory:"음식/주류",',
    parentCategory: "ESG 뉴스",
    childCategory: "음식/주류",
    reporter: "뉴스럴",
    title:
      '"젊어진 새우깡·더 매운 신라면"…MZ 입맛 따라 변화하는 식품업계 스테디셀러',
    link: "https://www.neusral.com/r?n=gpCkMwNOLV",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"세븐브로이, ‘곰표’ 딱지 떼기 본격화…“논알콜 맥주‧기능성음료 확대”",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=dQCxrEpzKE",date:"23.11.20",childCategory:"음식/주류",',
    parentCategory: "ESG 뉴스",
    childCategory: "음식/주류",
    reporter: "뉴스럴",
    title: "세븐브로이, ‘곰표’ 딱지 떼기 본격화…“논알콜 맥주‧기능성음료 확대”",
    link: "https://www.neusral.com/r?n=dQCxrEpzKE",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"국순당, 라인프렌즈 캐릭터 담은 막걸리 일본·대만 수출",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=JbCMXaQ8zJ",date:"23.11.20",childCategory:"음식/주류",',
    parentCategory: "ESG 뉴스",
    childCategory: "음식/주류",
    reporter: "뉴스럴",
    title: "국순당, 라인프렌즈 캐릭터 담은 막걸리 일본·대만 수출",
    link: "https://www.neusral.com/r?n=JbCMXaQ8zJ",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"‘제로 열풍’ 타고 서울 온 선양소주…“수도권 1%에 올인”",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=OMCOMXYNLW",date:"23.11.20",childCategory:"음식/주류",',
    parentCategory: "ESG 뉴스",
    childCategory: "음식/주류",
    reporter: "뉴스럴",
    title: "‘제로 열풍’ 타고 서울 온 선양소주…“수도권 1%에 올인”",
    link: "https://www.neusral.com/r?n=OMCOMXYNLW",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"큐원 ‘상쾌환’, 숙취해소 시장의 ‘대표 브랜드’가 되다",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=aVCVRMKWQ6",date:"23.11.20",childCategory:"음식/주류",',
    parentCategory: "ESG 뉴스",
    childCategory: "음식/주류",
    reporter: "뉴스럴",
    title: "큐원 ‘상쾌환’, 숙취해소 시장의 ‘대표 브랜드’가 되다",
    link: "https://www.neusral.com/r?n=aVCVRMKWQ6",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"주류 앱 ‘달리’, 제휴 매장 주류 판매 ‘오늘짠’ 서비스 론칭",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=A4Cy8ApeJm",date:"23.11.20",childCategory:"음식/주류",',
    parentCategory: "ESG 뉴스",
    childCategory: "음식/주류",
    reporter: "뉴스럴",
    title: "주류 앱 ‘달리’, 제휴 매장 주류 판매 ‘오늘짠’ 서비스 론칭",
    link: "https://www.neusral.com/r?n=A4Cy8ApeJm",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"[부동산 돋보기] 엔데믹 이후 서울 TOP3 상권은…압구정·한남·성수",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=aVCVRMKB3a",date:"23.11.20",childCategory:"주거/공간",',
    parentCategory: "ESG 뉴스",
    childCategory: "주거/공간",
    reporter: "뉴스럴",
    title: "[부동산 돋보기] 엔데믹 이후 서울 TOP3 상권은…압구정·한남·성수",
    link: "https://www.neusral.com/r?n=aVCVRMKB3a",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"\\"더현대서울·한강공원 좋아\\"…여의도, 외국인 핫플로 떴다",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=KYCzjo40XZ",date:"23.11.17",childCategory:"주거/공간",',
    parentCategory: "ESG 뉴스",
    childCategory: "주거/공간",
    reporter: "뉴스럴",
    title: '"더현대서울·한강공원 좋아"…여의도, 외국인 핫플로 떴다',
    link: "https://www.neusral.com/r?n=KYCzjo40XZ",
    date: "23.11.17",
    description: undefined,
  },
  {
    id: '#title:"“유럽 1번 갈 바에 한국 5번 간다”...日 관광객이 우리나라에 몰리는 이유 [여행가중계]",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=aVCVRMKn3z",date:"23.11.20",childCategory:"문화/생활/여행",',
    parentCategory: "ESG 뉴스",
    childCategory: "문화/생활/여행",
    reporter: "뉴스럴",
    title:
      "“유럽 1번 갈 바에 한국 5번 간다”...日 관광객이 우리나라에 몰리는 이유 [여행가중계]",
    link: "https://www.neusral.com/r?n=aVCVRMKn3z",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"LG전자 “스니커즈팬 잡아라”…美서 신발관리기 선보여",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=gpCkMw6bz4",date:"23.11.20",childCategory:"가전/전자",',
    parentCategory: "ESG 뉴스",
    childCategory: "가전/전자",
    reporter: "뉴스럴",
    title: "LG전자 “스니커즈팬 잡아라”…美서 신발관리기 선보여",
    link: "https://www.neusral.com/r?n=gpCkMw6bz4",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"내가 만드는 디지털 통신 플랫폼 '너겟'…MZ 공략 나선 LG유플러스",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=XJCeWozRRO",date:"23.11.20",childCategory:"가전/전자",`,
    parentCategory: "ESG 뉴스",
    childCategory: "가전/전자",
    reporter: "뉴스럴",
    title: "내가 만드는 디지털 통신 플랫폼 '너겟'…MZ 공략 나선 LG유플러스",
    link: "https://www.neusral.com/r?n=XJCeWozRRO",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"[단독] 네이버, 게임시장 다시 발들인다…생중계 플랫폼 내년 출시 | 팩플",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://news.koreadaily.com/2023/11/20/economy/business/20231120120114272.html",date:"23.11.21",childCategory:"출시/성과",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title:
      "[단독] 네이버, 게임시장 다시 발들인다…생중계 플랫폼 내년 출시 | 팩플",
    link: "https://news.koreadaily.com/2023/11/20/economy/business/20231120120114272.html",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"카카오엔터프라이즈, 전북 공공기관 디지털 전환 지원",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=eWCWL1a1P8",date:"23.11.20",childCategory:"출시/성과",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title: "카카오엔터프라이즈, 전북 공공기관 디지털 전환 지원",
    link: "https://www.neusral.com/r?n=eWCWL1a1P8",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"카카오엔터, K콘텐츠 신예 발굴…'드라마·영화 공모전' 11편 수상",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://mobile.newsis.com/view.html?ar_id=NISX20231120_0002527977",date:"23.11.20",childCategory:"출시/성과",`,
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title: "카카오엔터, K콘텐츠 신예 발굴…'드라마·영화 공모전' 11편 수상",
    link: "https://mobile.newsis.com/view.html?ar_id=NISX20231120_0002527977",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"‘샐리’와 ‘코니’가 막걸리에… 국순당 ‘라인프렌즈 막걸리’, 일본‧대만 수출길",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.donga.com/news/Economy/article/all/20231120/122269330/1",date:"23.11.20",childCategory:"출시/성과",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title:
      "‘샐리’와 ‘코니’가 막걸리에… 국순당 ‘라인프렌즈 막걸리’, 일본‧대만 수출길",
    link: "https://www.donga.com/news/Economy/article/all/20231120/122269330/1",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"배민 '한집배달', '알뜰배달'과 함께 배차 가능…배송 속도는?",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://mobile.newsis.com/view.html?ar_id=NISX20231120_0002527290",date:"23.11.20",childCategory:"출시/성과",`,
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title: "배민 '한집배달', '알뜰배달'과 함께 배차 가능…배송 속도는?",
    link: "https://mobile.newsis.com/view.html?ar_id=NISX20231120_0002527290",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"토스페이, 42개 국가서 오프라인 결제 서비스",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.hankyung.com/article/2023112006611",date:"23.11.20",childCategory:"출시/성과",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title: "토스페이, 42개 국가서 오프라인 결제 서비스",
    link: "https://www.hankyung.com/article/2023112006611",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"토스뱅크, 사업 연속성 관리 국제 표준 인증 취득",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://biz.chosun.com/stock/finance/2023/11/20/Z6RDUV46Z5BNTBNGRQ2S4VBFNY/",date:"23.11.20",childCategory:"출시/성과",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title: "토스뱅크, 사업 연속성 관리 국제 표준 인증 취득",
    link: "https://biz.chosun.com/stock/finance/2023/11/20/Z6RDUV46Z5BNTBNGRQ2S4VBFNY/",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"'댓글 전쟁' 논란에…네이버, 대댓글 답글 나흘만에 철회",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=yMClegxRld",date:"23.11.20",childCategory:"경영/인사/이슈",`,
    parentCategory: "ESG 뉴스",
    childCategory: "경영/인사/이슈",
    reporter: "뉴스럴",
    title: "'댓글 전쟁' 논란에…네이버, 대댓글 답글 나흘만에 철회",
    link: "https://www.neusral.com/r?n=yMClegxRld",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"다음달, 인뱅 내년도 중저신용자 대출 계획 나온다",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://byline.network/2023/11/20-303/",date:"23.11.20",childCategory:"경영/인사/이슈",',
    parentCategory: "ESG 뉴스",
    childCategory: "경영/인사/이슈",
    reporter: "뉴스럴",
    title: "다음달, 인뱅 내년도 중저신용자 대출 계획 나온다",
    link: "https://byline.network/2023/11/20-303/",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"카카오, 4차 비상 경영 회의...오는 23일 위원회 첫 회동",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=qkCZqYA6wG",date:"23.11.20",childCategory:"경영/인사/이슈",',
    parentCategory: "ESG 뉴스",
    childCategory: "경영/인사/이슈",
    reporter: "뉴스럴",
    title: "카카오, 4차 비상 경영 회의...오는 23일 위원회 첫 회동",
    link: "https://www.neusral.com/r?n=qkCZqYA6wG",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"김태중 쿠팡 부사장 임명 5개월만에 사임",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=eWCWL1aWw1",date:"23.11.20",childCategory:"경영/인사/이슈",',
    parentCategory: "ESG 뉴스",
    childCategory: "경영/인사/이슈",
    reporter: "뉴스럴",
    title: "김태중 쿠팡 부사장 임명 5개월만에 사임",
    link: "https://www.neusral.com/r?n=eWCWL1aWw1",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"\\"갑자기 내 신용점수가 왜?\\"…토스뱅크, 신용정보 전달 오류 사고",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.news1.kr/articles/?5237039",date:"23.11.20",childCategory:"경영/인사/이슈",',
    parentCategory: "ESG 뉴스",
    childCategory: "경영/인사/이슈",
    reporter: "뉴스럴",
    title: '"갑자기 내 신용점수가 왜?"…토스뱅크, 신용정보 전달 오류 사고',
    link: "https://www.news1.kr/articles/?5237039",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"클로바X·클로바노트·큐 고도화…AI '다 계획이 있는' 네이버",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=dQCxrEMkpG",date:"23.11.20",childCategory:"기술/R&D",`,
    parentCategory: "ESG 뉴스",
    childCategory: "기술/R&D",
    reporter: "뉴스럴",
    title: "클로바X·클로바노트·큐 고도화…AI '다 계획이 있는' 네이버",
    link: "https://www.neusral.com/r?n=dQCxrEMkpG",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"협업툴 카카오워크, “공공시장 포기”…CSAP 인증 취소",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=47CpozxLp3",date:"23.11.21",childCategory:"기술/R&D",',
    parentCategory: "ESG 뉴스",
    childCategory: "기술/R&D",
    reporter: "뉴스럴",
    title: "협업툴 카카오워크, “공공시장 포기”…CSAP 인증 취소",
    link: "https://www.neusral.com/r?n=47CpozxLp3",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"카카오모빌리티 불공정 논란 개선… 김범수, 4차 공동체 경영회의 진행",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=NACn3VPjwP",date:"23.11.20",childCategory:"채용/기업문화",',
    parentCategory: "ESG 뉴스",
    childCategory: "채용/기업문화",
    reporter: "뉴스럴",
    title: "카카오모빌리티 불공정 논란 개선… 김범수, 4차 공동체 경영회의 진행",
    link: "https://www.neusral.com/r?n=NACn3VPjwP",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"열화상 비전 솔루션 스타트업 ‘써모아이㈜’, PRE-A 투자 유치",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=r1CndqGRlB",date:"23.11.20",childCategory:"투자 유치",',
    parentCategory: "ESG 뉴스",
    childCategory: "투자 유치",
    reporter: "뉴스럴",
    title: "열화상 비전 솔루션 스타트업 ‘써모아이㈜’, PRE-A 투자 유치",
    link: "https://www.neusral.com/r?n=r1CndqGRlB",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"창업 4개월 만에 CES 혁신상... 아이디어오션, 시드 투자 유치[김종우의 VC 투자노트]",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=47Cpozg0OO",date:"23.11.20",childCategory:"투자 유치",',
    parentCategory: "ESG 뉴스",
    childCategory: "투자 유치",
    reporter: "뉴스럴",
    title:
      "창업 4개월 만에 CES 혁신상... 아이디어오션, 시드 투자 유치[김종우의 VC 투자노트]",
    link: "https://www.neusral.com/r?n=47Cpozg0OO",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"아이블소프트, 최대 10억 금융 지원 받을 수 있는 신용보증기금 ‘스텝업 도전기업’에 선정돼",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=aVCVRM4rzM",date:"23.11.20",childCategory:"출시/성과",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title:
      "아이블소프트, 최대 10억 금융 지원 받을 수 있는 신용보증기금 ‘스텝업 도전기업’에 선정돼",
    link: "https://www.neusral.com/r?n=aVCVRM4rzM",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"김인용 엠플 대표 \\"K뷰티 카르텔 없앤 플랫폼…누적 거래 400억원\\"",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=joCVNMZJPP",date:"23.11.21",childCategory:"출시/성과",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title: '김인용 엠플 대표 "K뷰티 카르텔 없앤 플랫폼…누적 거래 400억원"',
    link: "https://www.neusral.com/r?n=joCVNMZJPP",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"\\"운전자에게 필요한 슈퍼앱 되겠다\\"…차봇, 앱 전면 개편",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=k4CQnM463V",date:"23.11.20",childCategory:"출시/성과",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title: '"운전자에게 필요한 슈퍼앱 되겠다"…차봇, 앱 전면 개편',
    link: "https://www.neusral.com/r?n=k4CQnM463V",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"서빙로봇 ‘브이디컴퍼니’, 자율주행 로봇 서비스 ‘뉴빌리티’와 실내외 자율주행 로봇 기능 개발 협력",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=GkCGK60aBE",date:"23.11.20",childCategory:"출시/성과",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title:
      "서빙로봇 ‘브이디컴퍼니’, 자율주행 로봇 서비스 ‘뉴빌리티’와 실내외 자율주행 로봇 기능 개발 협력",
    link: "https://www.neusral.com/r?n=GkCGK60aBE",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"와이즈에이아이, 유앤아이의원 27개 지점에 AI 고객센터 공급",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=yMClegxPYw",date:"23.11.20",childCategory:"출시/성과",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title: "와이즈에이아이, 유앤아이의원 27개 지점에 AI 고객센터 공급",
    link: "https://www.neusral.com/r?n=yMClegxPYw",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"크리에이트립, 외국인 관광객 대상 서울시 '혼밥패스' 출시",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=joCVNMYyKq",date:"23.11.20",childCategory:"출시/성과",`,
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title: "크리에이트립, 외국인 관광객 대상 서울시 '혼밥패스' 출시",
    link: "https://www.neusral.com/r?n=joCVNMYyKq",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"네이처모빌리티, 초소형 전기차 관련 산학연 MOU 체결",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=YKCRY78jAn",date:"23.11.20",childCategory:"출시/성과",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title: "네이처모빌리티, 초소형 전기차 관련 산학연 MOU 체결",
    link: "https://www.neusral.com/r?n=YKCRY78jAn",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"오비고-어플레이즈, 차량용 개인화 음악서비스 개발사업 MOU 체결",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=YKCRY7LWqk",date:"23.11.20",childCategory:"출시/성과",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title: "오비고-어플레이즈, 차량용 개인화 음악서비스 개발사업 MOU 체결",
    link: "https://www.neusral.com/r?n=YKCRY7LWqk",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"서울먹거리창업센터 스마트양식 스타트업 '익투스AI', 전남대와 MOU",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=xACA7L1k8p",date:"23.11.20",childCategory:"출시/성과",`,
    parentCategory: "ESG 뉴스",
    childCategory: "출시/성과",
    reporter: "뉴스럴",
    title: "서울먹거리창업센터 스마트양식 스타트업 '익투스AI', 전남대와 MOU",
    link: "https://www.neusral.com/r?n=xACA7L1k8p",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"중진공, 유망 중기 지원해 민간후속투자 누적 1조7000억 달성",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=OMCOMX7AYQ",date:"23.11.20",childCategory:"지원프로그램",',
    parentCategory: "ESG 뉴스",
    childCategory: "지원프로그램",
    reporter: "뉴스럴",
    title: "중진공, 유망 중기 지원해 민간후속투자 누적 1조7000억 달성",
    link: "https://www.neusral.com/r?n=OMCOMX7AYQ",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"농식품모태펀드, 2027년까지 1000억 투자금 조성",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=oZCdVzKleK",date:"23.11.20",childCategory:"지원프로그램",',
    parentCategory: "ESG 뉴스",
    childCategory: "지원프로그램",
    reporter: "뉴스럴",
    title: "농식품모태펀드, 2027년까지 1000억 투자금 조성",
    link: "https://www.neusral.com/r?n=oZCdVzKleK",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"하나금융, 1호 민간 벤처모펀드 '1000억' 조성…투자 촉진 기대",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=3jCAR8J3QA",date:"23.11.20",childCategory:"지원프로그램",`,
    parentCategory: "ESG 뉴스",
    childCategory: "지원프로그램",
    reporter: "뉴스럴",
    title: "하나금융, 1호 민간 벤처모펀드 '1000억' 조성…투자 촉진 기대",
    link: "https://www.neusral.com/r?n=3jCAR8J3QA",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"\\"나흘새 40원 '뚝'\\"…원달러 환율, 1270원대로 가나",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=lnCWqOx3p0",date:"23.11.21",childCategory:"증시/환율",`,
    parentCategory: "ESG 뉴스",
    childCategory: "증시/환율",
    reporter: "뉴스럴",
    title: `"나흘새 40원 '뚝'"…원달러 환율, 1270원대로 가나`,
    link: "https://www.neusral.com/r?n=lnCWqOx3p0",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: `#title:"공매도 금지했는데…개미, 해외로 '머니 무브'",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=EZCYn6Lezp",date:"23.11.20",childCategory:"증시/환율",`,
    parentCategory: "ESG 뉴스",
    childCategory: "증시/환율",
    reporter: "뉴스럴",
    title: "공매도 금지했는데…개미, 해외로 '머니 무브'",
    link: "https://www.neusral.com/r?n=EZCYn6Lezp",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"\\"공매도 잔고 여전히 높아…개미 선호 업종 관심둬야\\"",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=GkCGK60pq3",date:"23.11.21",childCategory:"증시/환율",',
    parentCategory: "ESG 뉴스",
    childCategory: "증시/환율",
    reporter: "뉴스럴",
    title: '"공매도 잔고 여전히 높아…개미 선호 업종 관심둬야"',
    link: "https://www.neusral.com/r?n=GkCGK60pq3",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"논란의 기술특례 상장사, 매출 달성률 평균 32% 불과…실적 부풀리기 후유증?",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=ROCyaRzpMo",date:"23.11.21",childCategory:"증시/환율",',
    parentCategory: "ESG 뉴스",
    childCategory: "증시/환율",
    reporter: "뉴스럴",
    title:
      "논란의 기술특례 상장사, 매출 달성률 평균 32% 불과…실적 부풀리기 후유증?",
    link: "https://www.neusral.com/r?n=ROCyaRzpMo",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"샘 올트먼 영입한 MS, 2% 대 상승…나스닥 1.13%↑[데일리국제금융시장]",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=ROCyaRzb01",date:"23.11.21",childCategory:"증시/환율",',
    parentCategory: "ESG 뉴스",
    childCategory: "증시/환율",
    reporter: "뉴스럴",
    title: "샘 올트먼 영입한 MS, 2% 대 상승…나스닥 1.13%↑[데일리국제금융시장]",
    link: "https://www.neusral.com/r?n=ROCyaRzb01",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"전기료·외식비 고공행진, 서울 물가 가장 많이 올랐다",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=lnCWqOxwyj",date:"23.11.21",childCategory:"금리/부동산/물가",',
    parentCategory: "ESG 뉴스",
    childCategory: "금리/부동산/물가",
    reporter: "뉴스럴",
    title: "전기료·외식비 고공행진, 서울 물가 가장 많이 올랐다",
    link: "https://www.neusral.com/r?n=lnCWqOxwyj",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"‘극과극’ 집값 전망에… 전셋값만 오른다",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=eWCWL1apEX",date:"23.11.21",childCategory:"금리/부동산/물가",',
    parentCategory: "ESG 뉴스",
    childCategory: "금리/부동산/물가",
    reporter: "뉴스럴",
    title: "‘극과극’ 집값 전망에… 전셋값만 오른다",
    link: "https://www.neusral.com/r?n=eWCWL1apEX",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"내년 회사채 만기 역대 최대…발행 쏟아지나",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=GkCGK60glp",date:"23.11.21",childCategory:"금리/부동산/물가",',
    parentCategory: "ESG 뉴스",
    childCategory: "금리/부동산/물가",
    reporter: "뉴스럴",
    title: "내년 회사채 만기 역대 최대…발행 쏟아지나",
    link: "https://www.neusral.com/r?n=GkCGK60glp",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: `#title:"美·EU는 '디스인플레', 韓은 전망치 줄상향…\\"고금리 길어진다\\"",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=zRCyJmKqx6",date:"23.11.21",childCategory:"금리/부동산/물가",`,
    parentCategory: "ESG 뉴스",
    childCategory: "금리/부동산/물가",
    reporter: "뉴스럴",
    title: `美·EU는 '디스인플레', 韓은 전망치 줄상향…"고금리 길어진다"`,
    link: "https://www.neusral.com/r?n=zRCyJmKqx6",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"다시 커지는 금리 인하 기대…현시점에서 살펴볼 4가지 쟁점 [조지원의 BOK리포트]",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=wLCEAm4BLw",date:"23.11.21",childCategory:"금리/부동산/물가",',
    parentCategory: "ESG 뉴스",
    childCategory: "금리/부동산/물가",
    reporter: "뉴스럴",
    title:
      "다시 커지는 금리 인하 기대…현시점에서 살펴볼 4가지 쟁점 [조지원의 BOK리포트]",
    link: "https://www.neusral.com/r?n=wLCEAm4BLw",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"韓 경제, 올해 실질GDP 바닥…5년간 연평균 성장률 2.2% 전망",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=LBCp1EdMgO",date:"23.11.21",childCategory:"전망/이슈",',
    parentCategory: "ESG 뉴스",
    childCategory: "전망/이슈",
    reporter: "뉴스럴",
    title: "韓 경제, 올해 실질GDP 바닥…5년간 연평균 성장률 2.2% 전망",
    link: "https://www.neusral.com/r?n=LBCp1EdMgO",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"韓 최대 수출시장 中→美?…20년 만에 1위 자리 바뀌나",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=k4CQnM4agR",date:"23.11.21",childCategory:"전망/이슈",',
    parentCategory: "ESG 뉴스",
    childCategory: "전망/이슈",
    reporter: "뉴스럴",
    title: "韓 최대 수출시장 中→美?…20년 만에 1위 자리 바뀌나",
    link: "https://www.neusral.com/r?n=k4CQnM4agR",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"사우디 내년까지 감산 연장 검토…국제 유가 또 오르나",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=Z2C0oGMedK",date:"23.11.21",childCategory:"전망/이슈",',
    parentCategory: "ESG 뉴스",
    childCategory: "전망/이슈",
    reporter: "뉴스럴",
    title: "사우디 내년까지 감산 연장 검토…국제 유가 또 오르나",
    link: "https://www.neusral.com/r?n=Z2C0oGMedK",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: `#title:"경기침체에 닫히는 지갑 속…'편의점-백화점' 전망 엇갈리는 이유",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=NACn3VPlzP",date:"23.11.21",childCategory:"전망/이슈",`,
    parentCategory: "ESG 뉴스",
    childCategory: "전망/이슈",
    reporter: "뉴스럴",
    title: "경기침체에 닫히는 지갑 속…'편의점-백화점' 전망 엇갈리는 이유",
    link: "https://www.neusral.com/r?n=NACn3VPlzP",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: `#title:"'챗GPT' 샘 올트먼, 오픈AI 해임후 MS 합류…새 AI팀 이끈다(종합)",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=aVCVRMKNBP",date:"23.11.20",childCategory:"챗GPT/생성AI",`,
    parentCategory: "ESG 뉴스",
    childCategory: "챗GPT/생성AI",
    reporter: "뉴스럴",
    title: "'챗GPT' 샘 올트먼, 오픈AI 해임후 MS 합류…새 AI팀 이끈다(종합)",
    link: "https://www.neusral.com/r?n=aVCVRMKNBP",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"오픈AI 직원 대부분, 이사 전원 사임 촉구…\\"안 되면 MS 가겠다\\"",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=MLC6zLJ00g",date:"23.11.21",childCategory:"챗GPT/생성AI",',
    parentCategory: "ESG 뉴스",
    childCategory: "챗GPT/생성AI",
    reporter: "뉴스럴",
    title: '오픈AI 직원 대부분, 이사 전원 사임 촉구…"안 되면 MS 가겠다"',
    link: "https://www.neusral.com/r?n=MLC6zLJ00g",
    date: "23.11.21",
    description: undefined,
  },
  {
    id: '#title:"오픈AI 새 CEO 에멧은 누구…“실리콘밸리 고위 인사가 강력 추천”",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=23CPK8GZrA",date:"23.11.20",childCategory:"챗GPT/생성AI",',
    parentCategory: "ESG 뉴스",
    childCategory: "챗GPT/생성AI",
    reporter: "뉴스럴",
    title: "오픈AI 새 CEO 에멧은 누구…“실리콘밸리 고위 인사가 강력 추천”",
    link: "https://www.neusral.com/r?n=23CPK8GZrA",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"클로바X·클로바노트·큐 고도화…AI '다 계획이 있는' 네이버",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=dQCxrEMkpG",date:"23.11.20",childCategory:"출시/개발",`,
    parentCategory: "ESG 뉴스",
    childCategory: "출시/개발",
    reporter: "뉴스럴",
    title: "클로바X·클로바노트·큐 고도화…AI '다 계획이 있는' 네이버",
    link: "https://www.neusral.com/r?n=dQCxrEMkpG",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"셀바스 그룹, 메디아나 인수 'AI 의료 얼라이언스 구축'",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=lnCWqOxOQG",date:"23.11.20",childCategory:"출시/개발",`,
    parentCategory: "ESG 뉴스",
    childCategory: "출시/개발",
    reporter: "뉴스럴",
    title: "셀바스 그룹, 메디아나 인수 'AI 의료 얼라이언스 구축'",
    link: "https://www.neusral.com/r?n=lnCWqOxOQG",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"\\"게임을 더욱 생생하게\\"…지스타 '신 스틸러'로 활약한 AI",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=YKCRY78L83",date:"23.11.20",childCategory:"출시/개발",`,
    parentCategory: "ESG 뉴스",
    childCategory: "출시/개발",
    reporter: "뉴스럴",
    title: `"게임을 더욱 생생하게"…지스타 '신 스틸러'로 활약한 AI`,
    link: "https://www.neusral.com/r?n=YKCRY78L83",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"보안체계 강화 나선 LG CNS…MS 생성형 AI '코파일럿' 적용",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=gpCkMw661a",date:"23.11.20",childCategory:"출시/개발",`,
    parentCategory: "ESG 뉴스",
    childCategory: "출시/개발",
    reporter: "뉴스럴",
    title: "보안체계 강화 나선 LG CNS…MS 생성형 AI '코파일럿' 적용",
    link: "https://www.neusral.com/r?n=gpCkMw661a",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"롯데정보통신 'AI 상담' 한국어 AI 경진대회 1위",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=wLCEAm4MdL",date:"23.11.20",childCategory:"출시/개발",`,
    parentCategory: "ESG 뉴스",
    childCategory: "출시/개발",
    reporter: "뉴스럴",
    title: "롯데정보통신 'AI 상담' 한국어 AI 경진대회 1위",
    link: "https://www.neusral.com/r?n=wLCEAm4MdL",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"뉴렐릭, AI용 APM 솔루션 출시",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=68Ce0yXLZX",date:"23.11.20",childCategory:"출시/개발",',
    parentCategory: "ESG 뉴스",
    childCategory: "출시/개발",
    reporter: "뉴스럴",
    title: "뉴렐릭, AI용 APM 솔루션 출시",
    link: "https://www.neusral.com/r?n=68Ce0yXLZX",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: '#title:"\\"AI 인재 수, 한국 30개국 중 22위…미·중 벤치마킹 필요\\"",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=EZCYn6kM6Z",date:"23.11.20",childCategory:"현상/규제/전망",',
    parentCategory: "ESG 뉴스",
    childCategory: "현상/규제/전망",
    reporter: "뉴스럴",
    title: '"AI 인재 수, 한국 30개국 중 22위…미·중 벤치마킹 필요"',
    link: "https://www.neusral.com/r?n=EZCYn6kM6Z",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"\\"오픈AI 사태, '철학'차가 일으킨 분열\\"…AI 규제론 vs 개발론",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=LBCp1Ed7W6",date:"23.11.20",childCategory:"현상/규제/전망",`,
    parentCategory: "ESG 뉴스",
    childCategory: "현상/규제/전망",
    reporter: "뉴스럴",
    title: `"오픈AI 사태, '철학'차가 일으킨 분열"…AI 규제론 vs 개발론`,
    link: "https://www.neusral.com/r?n=LBCp1Ed7W6",
    date: "23.11.20",
    description: undefined,
  },
  {
    id: `#title:"아마존 '200만 AI 인력 양성' 추진...무료 온라인 프로그램 개설",reporter:"뉴스럴",parentCategory:"ESG 뉴스",link:"https://www.neusral.com/r?n=8XCjNZplkB",date:"23.11.21",childCategory:"현상/규제/전망",`,
    parentCategory: "ESG 뉴스",
    childCategory: "현상/규제/전망",
    reporter: "뉴스럴",
    title: "아마존 '200만 AI 인력 양성' 추진...무료 온라인 프로그램 개설",
    link: "https://www.neusral.com/r?n=8XCjNZplkB",
    date: "23.11.21",
    description: undefined,
  },
];
